language: node_js

node_js:
  - "0.10"

env:
  global:
    - secure: "JlzLHWXrxYI6hpxbI4X4mC5m7a0XcFeNQ/k2YS7o4P/vxaxEDpeX0cL9IBFGmMDKQFWSI3EB4h/ebhSyl8WK/rHxxDUzzxfA+zCNP+4Nb8XNrU3wMujidWdMpCUwDdTMykgUCpgHoiKEqi3Dr9K1kq3BYJgdqMk0sh0sFbcD2U0="
    - GIT_REPO=jquery.visibilitytrigger.js
    - GIT_COMMITTER_NAME=Travis-CI
    - GIT_COMMITTER_EMAIL=Travis-CI
    - GIT_AUTHOR_NAME=falsandtru
    - GIT_AUTHOR_EMAIL=falsandtru

  matrix:
    - jquery=1.4.2
      deploy=false
    - jquery=1.7.2
      deploy=true
    - jquery=1.11.1
      deploy=false
    - jquery=2.1.1
      deploy=false

script:
  - grunt travis

after_success:
  - if [ $TRAVIS_BRANCH != "master" ] || [ ! $GH_TOKEN ]; then exit 0; fi
  - if [ $deploy == "false" ]; then exit 0; fi
  - mkdir ../gh-pages
  - cp -rf ./gh-pages ../
  - cp -rf ./test ../gh-pages
  - cat package.json | json version
  - new_version=`cat package.json | json version | awk -F. '{printf("%d%05d%06d", ++$1, $2, $3)}'`
  - git reset --hard HEAD~
  - cat package.json | json version
  - cat package.json | json version | awk -F. '{printf("%d%05d%06d", ++$1, $2, $3)}'
  - old_version=`cat package.json | json version | awk -F. '{printf("%d%05d%06d", ++$1, $2, $3)}'`
  - git reset --hard ORIG_HEAD
  - if [ $new_version -lt $old_version ]; then exit 0; fi
  - git fetch origin gh-pages:gh-pages
  - git checkout --orphan gh-pages
  - git checkout -m gh-pages
  - ls -a | grep -vE "^.git$|^\.+$" | xargs rm -rf
  - cp -rf ../gh-pages/* ./
  - find | grep -vE "^./.git(/|$)"
  - git add -A :/
  - git commit -m 'Deploy by Travis-CI'
  - git push https://${GH_TOKEN}@github.com/${GIT_AUTHOR_NAME}/${GIT_REPO}.git gh-pages:gh-pages 2>&1 | sed -e "s/:\/\/\w\+@/:\/\/[secure]@/g"
  
notifications:
  email:
    recipients:
      - secure: "YFEPmZeA6ts1k6KU09EIxCtyV9ot3TM/S2+vielLpUXTrgFt2MnWptWyHWnl9Ge4QcyUTi6RiiR3DC8w7THm454DEXvEoQvwKSLgNZhADpTv7yJPJpqF/Ld9+zwKDIUB62RFNCj5urmAF/7hXYvVvyufTlIhY54KuHnyKV1jaQw="
    on_success: change # default: change
    on_failure: always # default: always
