language: node_js

node_js:
  - "0.10"

env:
  global:
    - secure: "Twxs/SZnM+JxHuZ8xtENBOb4BnchKn4p152r8YSPObipTfWwr2D+byA+KmCesyQLG8uXmlCP4dyOe4WNowP7NalE+ey57Xxk6XT43EYixCMEt5yEo6MHxoL+eXQDFaZjd/cvnizC7ujg2g34vvwN4sPoVKIG/2Ug/gzY4T/BR10="
    - GIT_REPO=jquery-visibilitytrigger
    - GIT_COMMITTER_NAME=Travis-CI
    - GIT_COMMITTER_EMAIL=Travis-CI
    - GIT_AUTHOR_NAME=falsandtru
    - GIT_AUTHOR_EMAIL=falsandtru

  matrix:
    - jquery=1.4.2
      deploy=false
    - jquery=1.7.2
      deploy=true
    - jquery=1.11.1
      deploy=false
    - jquery=2.1.1
      deploy=false

script:
  - grunt travis

after_success:
  - if [ $TRAVIS_BRANCH != "master" ] || [ ! $GH_TOKEN ]; then exit 0; fi
  - if [ $deploy == "false" ]; then exit 0; fi
  - mkdir ../gh-pages
  - cp -rf ./gh-pages ../
  - cp -rf ./test ../gh-pages
  - cat package.json | json version
  - new_version=`cat package.json | json version | awk -F. '{printf("%d%05d%06d", ++$1, $2, $3)}'`
  - git reset --hard HEAD~
  - cat package.json | json version
  - cat package.json | json version | awk -F. '{printf("%d%05d%06d", ++$1, $2, $3)}'
  - old_version=`cat package.json | json version | awk -F. '{printf("%d%05d%06d", ++$1, $2, $3)}'`
  - git reset --hard ORIG_HEAD
  - if [ $new_version -lt $old_version ]; then exit 0; fi
  - git fetch origin gh-pages:gh-pages
  - git checkout --orphan gh-pages
  - git checkout -m gh-pages
  - ls -a | grep -vE "^.git$|^\.+$" | xargs rm -rf
  - cp -rf ../gh-pages/* ./
  - find | grep -vE "^./.git(/|$)"
  - git add -A :/
  - git commit -m 'Deploy by Travis-CI'
  - git push https://${GH_TOKEN}@github.com/${GIT_AUTHOR_NAME}/${GIT_REPO}.git gh-pages:gh-pages 2>&1 | sed -e "s/:\/\/\w\+@/:\/\/[secure]@/g"
  
notifications:
  email:
    recipients:
      - secure: "GeQilEMqBRwI5gXSN4Xw4ZEoPws23vHFs1rdmFAVZAAykQ+FzCalYFK/pJ0xNmYJOf/44X/bLU4bihLTrgd2vcH8JC8vd/3xbV3jgOJ+Cmz6o9wjInvW9gpSEBmTAAPoDaOkZ8cnEYwSATE2EKAlkZ4eJXdxfxNJW7YnCV9LSac="
    on_success: change # default: change
    on_failure: always # default: always
